### PR TITLE
Letsencrypt doesn't support 4096bit keys

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by jtolio** [comment]
really? why? since when?

**Comment by DanielHeath** [comment]
Don't think it was ever supported.

**Comment by jtolio** [comment]
https://letsencrypt.org/getting-started/ strongly implies support for 4096 keys. i'd love to know more about why you think they aren't supported. 4096 bit keys are much more secure, and this works for me and others that have tested it

**Comment by DanielHeath** [comment]
https://github.com/ericchiang/letsencrypt/blob/master/acme.go#L446 refers to https://github.com/letsencrypt/boulder/issues/1592 - specifically for account keys.

**Comment by jtolio** [comment]
sure, and then https://github.com/letsencrypt/boulder/issues/1592#issuecomment-195637450 points out 4096 bit keys are supported.

**Comment by DanielHeath** [comment]
https://github.com/ericchiang/letsencrypt/blob/master/acme.go#L446 returns `errUnsupportedRSABitLen` for 4096 keys.

**Comment by jtolio** [comment]
okay, i get it, you're saying that even though letsencrypt works with 4096 bit keys, AND the binary I have of lecat works with 4096 keys, it must be the case that between the time I built my working lecat binary and now, the library i'm using (ericchiang/letsencrypt) stopped supporting 4096 bit keys for no real good reason, and so now recent builds of the client side library are failing.

okay, i'm so sorry to be so slow at understanding that. sure, let's merge this change until i switch to rsc's library

**Comment by DanielHeath** [comment]
I think there might be a difference between account keys and the certs presented to browsers? Not 100% clear on the issue but this sorted it out so I didn't dig much further.

**Comment by jtolio** [comment]
well either way, i bet trying to get me to understand the issue was really frustrating lol. sorry again for being so slow

**Comment by DanielHeath** [comment]
no worries! thanks for lecat :)

**Comment by jtolio** [comment]
heh no problem!

**Pull request merged**
